# Image tag includes branch name (sanitized: / → -) and commit SHA for traceability.
# BRANCH_NAME and COMMIT_SHA are provided by Cloud Build when triggered from a branch.
steps:
# Build the container image (tag: client-<branch>-<sha>)
- name: "gcr.io/cloud-builders/docker"
  entrypoint: bash
  args:
    - -c
    - |
      cd natalia-dojo-website
      SAFE_BRANCH=$(echo "${BRANCH_NAME:-main}" | tr '/' '-')
      IMAGE="me-west1-docker.pkg.dev/${PROJECT_ID}/dojo-website/natalia:client-${SAFE_BRANCH}-${COMMIT_SHA}"
      docker build -t "$IMAGE" .
      docker push "$IMAGE"
# Deploy container image to Cloud Run (same tag)
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: bash
  args:
    - -c
    - |
      SAFE_BRANCH=$(echo "${BRANCH_NAME:-main}" | tr '/' '-')
      IMAGE="me-west1-docker.pkg.dev/${PROJECT_ID}/dojo-website/natalia:client-${SAFE_BRANCH}-${COMMIT_SHA}"
      gcloud beta run deploy natalia --image="$IMAGE" --region=us-central1 --port=8080 --platform=managed --min-instances=1 --max-instances=1 --allow-unauthenticated
# Fix: build must use CLOUD_LOGGING_ONLY when service_account / logs_bucket not set
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'me-west1-docker.pkg.dev/$PROJECT_ID/dojo-website/natalia'
