# =============================================================================
# Dojo Natalia – Client (Angular SSR) – Cloud Build
# =============================================================================
# Builds the natalia-dojo-website Docker image (Angular 19 + SSR) and deploys
# it to Cloud Run.
#
# Image tag format: client-<branch>-<commit-sha>
#   - branch: Cloud Build BRANCH_NAME when set; else from git (abbrev-ref or
#     name-rev when detached HEAD). Slashes replaced with hyphens.
#   - commit-sha: full SHA (Cloud Build COMMIT_SHA).
# Example: client-update-to-9-fb3d72e76c5a8da40e277f5017eb49c37df2ac0e
#
# Commit message: last GitHub commit (git log -1); subject in log, full in label.
# =============================================================================

steps:
# Build the container image (tag: client-<branch>-<sha>)
- name: "gcr.io/cloud-builders/docker"
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      # Branch: prefer Cloud Build BRANCH_NAME; when detached HEAD use git name-rev to get branch containing this commit
      BRANCH="$${BRANCH_NAME}"
      if [ -z "$$BRANCH" ]; then
        BRANCH=$$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
        if [ "$$BRANCH" = "HEAD" ] || [ -z "$$BRANCH" ]; then
          BRANCH=$$(git name-rev --name-only HEAD 2>/dev/null | sed 's|remotes/origin/||;s/\^0$$//;s/~[0-9]*$$//' | head -1)
        fi
      fi
      SAFE_BRANCH=$$(echo "$${BRANCH:-main}" | tr '/' '-')
      # Message: last commit from GitHub (full for label; subject-only for log)
      COMMIT_MSG_FULL=$$(git log -1 --pretty=%B 2>/dev/null || echo 'n/a')
      COMMIT_MSG_SUBJECT=$$(git log -1 --pretty=%s 2>/dev/null || echo 'n/a')
      echo "=== Commit being built ==="
      echo "SHA:    ${COMMIT_SHA}"
      echo "Branch: $${SAFE_BRANCH}"
      echo "Message: $${COMMIT_MSG_SUBJECT}"
      echo "========================="
      cd natalia-dojo-website
      IMAGE="me-west1-docker.pkg.dev/${PROJECT_ID}/dojo-website/natalia:client-$${SAFE_BRANCH}-${COMMIT_SHA}"
      echo "$$IMAGE" > /workspace/.cloudbuild_image_tag
      # Image label: full GitHub commit message (sanitized: single line, no double quotes, max 20 chars)
      COMMIT_DESC=$$(echo "$$COMMIT_MSG_FULL" | tr '\n' ' ' | sed 's/"/'"'"'/g' | head -c 20)
      docker build -t "$$IMAGE" \
        --label "org.opencontainers.image.revision=${COMMIT_SHA}" \
        --label "org.opencontainers.image.description=$${COMMIT_DESC}" \
        .
      docker push "$$IMAGE"
# Deploy container image to Cloud Run (same tag as build)
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: bash
  args:
    - -c
    - |
      IMAGE=$$(cat /workspace/.cloudbuild_image_tag)
      gcloud beta run deploy natalia --image="$$IMAGE" --region=us-central1 --port=8080 --platform=managed --min-instances=1 --max-instances=1 --allow-unauthenticated
# Fix: build must use CLOUD_LOGGING_ONLY when service_account / logs_bucket not set
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'me-west1-docker.pkg.dev/$PROJECT_ID/dojo-website/natalia'
