version: '3.4'

services:
  nataliadojowebsite:
    image: nataliadojowebsite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
